src/Business/Grand.Business.Storage/Services/PictureService.cs
Resolves #100  
Type: bugfix
The current logic is to delete an image when it does not exist, so the image will never be removed
Change the logic to delete an image when it exists.
N/A
N/A
=> Fix for pictures - picture thumbs can not be deleted from local storage

src/API/Grand.Api/Infrastructure/DependencyEdmModel.cs
OData Client generated classes fail to fetch the layouts with the typo
There is a possible typo with the Layout namespaces.  
When classes are generated from /odata/$metadata these namespaces will not work to fetch the layouts from Grandnode
_Using the rest api without generated odata clients does work still..._
Typo changes in the DependencyEdmModel
No breaking changes - I believe - it is advised to _Update OData Connected Services_ in your consumer app.
After the change, and after updating the consumer app, it is possible to fetch layouts just fine
```cs
var layouts = ProductLayout.Execute();
```
=> Fix of possible typo - OData, API - ProductLayout, BrandLayout

src/Business/Grand.Business.Checkout/Commands/Handlers/Orders/PlaceOrderCommandHandler.cs
When trying to send a `OrderPlaced.CustomerNotification` MessageTemplate to the customer, I found that the `{{Order.PaymentMethod}}` variable is always empty.
After debugging the problem I found that in the `GetOrderTokensCommandHandler` the _paymentService returns the IPaymentMethod with `FriendlyName` always being an empty string
here: [GetOrderTokensCommandHandler.cs line 139](https://github.com/grandnode/grandnode2/blob/master/src/Business/Grand.Business.System/Commands/Handlers/Messages/GetOrderTokensCommandHandler.cs#L139)
```cs
var paymentMethod = _paymentService.LoadPaymentMethodBySystemName(request.Order.PaymentMethodSystemName);
liquidOrder.PaymentMethod = paymentMethod != null ? paymentMethod.FriendlyName : request.Order.PaymentMethodSystemName;
```
The issue turned out to be …
=> Populate a WorkContext in the created scope

src/Business/Grand.Business.Catalog/Services/Prices/PriceFormatter.cs
The Admin UI (Dashboard, Orders, etc..) does not respect the shop's currency locale - if currency custom formatting is set
The appropriate currency is still working in the shop UI, so there is no problem there.  
I believe this is because there is a default Culture set in the shop WorkContext (?) by the language or shop currency.  
However when the same PriceFormatter service is running for the Admin it uses default culture with the custom formatting.
I have HUF set as currency, display locale `hu-HU`, with custom formatting: `C0`  
In the shop I get a correct `3 980 Ft` as formatted price.  
In the admin UI this becomes `$3,980`  
This is because the PriceFormatter does not seem to handle the display locale  
when there is a custom formatting set.
I sending a suggestion for the fix.
=> The Admin UI does not respect the shop's currency locale

src/Business/Grand.Business.Checkout/Events/Orders/PaymentTransactionRefundedEvent.cs
Issue
In PaymentTransactionRefundedEvent.cs paymenttransaction returns null. Because of using wrong letter.
Your codes
public PaymentTransactionRefundedEvent(PaymentTransaction paymentTransaction, double amount)
{
PaymentTransaction = PaymentTransaction;
Amount = amount;
}
Solution
Change first latter of PaymentTransaction to lower
public PaymentTransactionRefundedEvent(PaymentTransaction paymentTransaction, double amount)
{
PaymentTransaction = paymentTransaction;
Amount = amount;
}
=> payment transaction null issue

src/Web/Grand.Web/Views/Product/_ProductAttributes.cshtml
When product attribute control type was image square,and if you setted additional fee not 0 for options,then there wasn't shown tooltips when mouse hover image square options in product details page.
Add missing id for image square
1. Add product attribute for one product,and set control type to image square.
2. Add option for the product attribute,and set additional fee not 0.
3. Show product details in shop page,move mouse hover the image square option.
=> fix product attribute image square tooltip

src/Web/Grand.Web/Controllers/BasePublicController.cs, src/Web/Grand.Web/Controllers/CommonController.cs, src/Web/Grand.Web/Endpoints/EndpointProvider.cs
Resolves #258 
Type: bugfix
Clear cart returns html instead of json
Add to the header reguest section: 'X-Response-View': 'Json'
Sample js code to return json instead of HTML:
axios({
baseURL: '/cart/clear',
method: 'get',
data: null,
headers: {
'Accept': 'application/json',
'Content-Type': 'application/json',
'X-Response-View': 'Json'
}
}).then(response => {
console.log(response);
});
=> Clear cart returns html instead of json #258 

src/Web/Grand.Web/Validators/Install/InstallValidator.cs
Type: feature
In the install page, if passwords are different it is exposing the password on error message
Set a generic error "Passwords must be equals".
Go to install page
Set different password and confirm password
Click on Install
=> Change password compare message

src/Web/Grand.Web/Views/Checkout/_ConfirmOrder.cshtml
Resolves #306 
In Checkout page on order conformation step. if terms and conditions is enabled back button is not working
Added missing click event to the button
none.
1. Enable terms and conditions at checkout setting in CMS .
2. Navigate to order conformation page after selecting payment method.
3. At order conformation step back button should navigate to payment selection method.
=> Check out order conformation back button click event added

src/Web/Grand.Web/wwwroot/theme/script/public.push.notifications.js
Resolves #308  
Push-notification process registration API call not properly handled in error condition, Two local variables are not available in error condition, So a console error getting logged in home page
Moved success and value variable to little above so that those are available in error condition as well.
None.
1. Navigate to Home page.
2. Check console logs , the following error "Uncaught (in promise) ReferenceError: success is not defined
at public.push.notifications.js:73:48" shouldn't print in consle
=> Push-notification process registration API call not properly handled in error condition

src/API/Grand.Api/Controllers/TokenWebController.cs
Resolves #318 
Not able to authenticate Frontend Web API using existing account, getting 400 "User not exists or password is wrong"
to fix change to LoginWebModel in TokenWebController so it refer to LoginWebValidator with customerService instead of LoginValidator with userApiService
none
POST call to http://yourstore.com/tokenweb/login with existing customer account
=> Bugfix in TokenWebController to LoginWebModel

src/Web/Grand.Web.Admin/Services/CustomerViewModelService.cs, src/Web/Grand.Web.Admin/Services/OrderViewModelService.cs
Resolves #324 
Address name field is shown even after disabling it under the customer setting
Replaced default true to  _addressSettings.NameEnabled field to check whether name enabled or not 
none.
1. Navigate to customer settings .
2. Goto Address Form Field section.
3. Based on the 'Address name' enabled Flag 'Address name' should populate.
=> Address name field is shown even after disabling it under the customer setting

src/Web/Grand.Web/Controllers/ProductController.cs
Resolves #issueNumber  
Reservation dates aren't displayed in the product's shop page if Product type is set to Reservation. Bad request errors are displayed while opening shop pages for Reservation products.
[HttpGet] attribute GetDatesForMonth action in ProductController is incorrect because fillAvailableDates, fillAvailableDatesFrom and fillAvailableDatesTo functions in public.common.js send POST requests to the backend controller.
None
1. Create new Product and set product type to Reservation.
2. Generate Reservation Calendar for the Product.
3. Check available reservation dates for the Product in the product's shop page.
=> Use POST method

src/Business/Grand.Business.Catalog/Services/Products/ProductAttributeFormatter.cs
Resolves #365
Type: **bugfix|**
When we order a bundled product, with any one or more bundled items having special characters in the name, the order invoice fails to generate. The Scryber library throws an error. 
Add Html encoding for the bundled product name
none.
1. Order a bundled product. At least one bundled item need to have a special character in the name.
2. Go to orders in admin and try to generate the invoice pdf. An error will be thrown
=> added HTML encoding for the Bundled product item name.

src/Business/Grand.Business.Catalog/Services/Products/ProductAttributeFormatter.cs
Resolves #376
The href on the bundled items will not work if the items are set to "Visible Individual" to false.
Check if the bundled item is Visible Individual, and decide to have anchor tags, if it's true only.
Code change: Moved the if else for htmlEncode check, as a conditional operator, for better readability.
none.
1.  Add a bundled product to cart
2. Set any one of the bundled item to Not visible Individually.
3. Go to cart, and try to click on the bundled item link
4. It will go to home page.
5. After the fix, if the product is not visible, href wont be added.
=> show hyperlink only if the product is individually visible.

src/Web/Grand.Web/Views/Product/Partials/AuctionInfo.cshtml
Resolves #387  
Bid option is not working in product detail page when auction product type is chosen. Because  AxiosCart.addbid function not able to identify form without product-id 
Appended product id to form so that , AxiosCart.addbid function will execute successfully  
None
1. Create a product with Auction product type with min and max bid price.
2. Navigate to product detail page and tap on Bid option. A successful bid option will get populated
=> product id appended to form

src/Core/Grand.Infrastructure/Configuration/AppConfig.cs, src/Core/Grand.Infrastructure/Configuration/ApplicationInsightsConfig.cs, src/Core/Grand.Infrastructure/Grand.Infrastructure.csproj, src/Core/Grand.Infrastructure/Plugins/PluginManager.cs, src/Core/Grand.Infrastructure/StartupBase.cs, src/Web/Grand.Web.Admin/App_Data/appsettings.json, src/Web/Grand.Web.Admin/Program.cs, src/Web/Grand.Web.Common/Infrastructure/BackgroundServiceTask.cs, src/Web/Grand.Web.Common/Infrastructure/ServiceCollectionExtensions.cs, src/Web/Grand.Web.Common/Middleware/ContextLoggingMiddleware.cs, src/Web/Grand.Web.Common/Startup/GrandCommonStartup.cs, src/Web/Grand.Web.Common/Startup/GrandMvcStartup.cs, src/Web/Grand.Web.Vendor/App_Data/appsettings.json, src/Web/Grand.Web.Vendor/Program.cs, src/Web/Grand.Web/App_Data/appsettings.json, src/Web/Grand.Web/Controllers/HomeController.cs, src/Web/Grand.Web/Program.cs
As part of the ongoing enhancements to our project, we have decided to remove Serilog, an integral logging component, from the core structure. This decision is driven by our commitment to flexibility and modularity in the project’s architecture.
Advantages of Removing Serilog:
Enhanced Customizability: By transitioning the logging functionality to a plugin-based approach, we provide users with the flexibility to choose or customize their logging solutions. This change aligns with modern development practices that favor adaptable and user-specific configurations.
Reduced Complexity: Integrating logging as a plugin rather than a core component simplifies the overall architecture of the project. This reduction in complexity makes the system more maintainable and easier to understand for new …
=> Remove serilog

src/Business/Grand.Business.Catalog/Services/Products/ProductsReportService.cs, src/Business/Grand.Business.Catalog/Startup/StartupApplication.cs, src/Business/Grand.Business.Checkout/Services/Orders/OrderReportService.cs, src/Business/Grand.Business.Checkout/Startup/StartupApplication.cs, src/Business/Grand.Business.Customers/Services/CustomerReportService.cs, src/Business/Grand.Business.Customers/Startup/StartupApplication.cs, src/Business/Grand.Business.System/Startup/StartupApplication.cs
Refactored report services by removing and re-adding `OrderReportService`,  `CustomerReportService`, `ProductsReportService`
=> Refactor and update report services

src/Modules/Grand.Module.Installer/Controllers/InstallController.cs, src/Modules/Grand.Module.Installer/Filters/DatabaseConfiguredAttribute.cs
Added DatabaseConfiguredAttribute.cs:
- Defined DatabaseConfiguredAttribute implementing IAsyncActionFilter to check database installation and handle action accordingly.
=> Refactor InstallController and add DatabaseConfigured attribute

Directory.Packages.props, src/Business/Grand.Business.Storage/Services/PictureService.cs
Updated various NuGet packages to their latest versions:
- AWSSDK.Core: 3.7.400.57 -> 3.7.400.59
- AWSSDK.S3: 3.7.407.1 -> 3.7.410.1
- SkiaSharp: 2.88.9 -> 3.116.1
- SkiaSharp.NativeAssets.Linux.NoDependencies: 2.88.9 -> 3.116.1
- LiteDB: 5.0.17 -> 5.0.21
- MongoDB.Bson: 3.0.0 -> 3.1.0
- MongoDB.Driver: 3.0.0 -> 3.1.0
- DotLiquid: 2.2.717 -> 2.3.0
- MassTransit: 8.3.2 -> 8.3.3
- MassTransit.RabbitMQ: 8.3.2 -> 8.3.3
- Microsoft.CodeAnalysis.CSharp: 4.11.0 -> 4.12.0
- Microsoft.CodeAnalysis.CSharp.Scripting: 4.11.0 -> 4.12.0
- StackExchange.Redis: 2.8.16 -> 2.8.22
- Swashbuckle.AspNetCore: 7.0.0 -> 7.1.0
- Swashbuckle.AspNetCore.Annotations: 7.0.0 -> 7.1.0
- Azure.Extensions.AspNetCore.DataProtection.Blobs: 1.3.4 -> 1.4.0
- Azure.Extensions.AspNetCore.DataProtection.Keys: 1.2.4 -> 1.3.0
- …
=> Update NuGet package versions in Directory.Packages.props

src/Web/Grand.Web.Admin/Controllers/SettingController.cs
Fixes [https://github.com/grandnode/grandnode2/security/code-scanning/311](https://github.com/grandnode/grandnode2/security/code-scanning/311)
To fix the problem, we need to ensure that the `directoryParam` does not contain any path traversal characters or sequences. We can achieve this by validating the `directoryParam` to ensure it does not contain any ".." sequences or path separators. Additionally, we should ensure that the `safeDirectoryName` is a valid directory name.
1. Validate the `directoryParam` to ensure it does not contain ".." or any path separators.
2. Ensure that the `safeDirectoryName` is a valid directory name.
3. Update the `GetSafeFilePath` method to include these validations.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 311: Uncontrolled data used in path expression

Directory.Packages.props, src/Modules/Grand.Module.Api/Grand.Module.Api.csproj
Updated the `Directory.Packages.props` file to change the versions of several package dependencies:
- `MailKit` from `4.8.0` to `4.9.0`
- `AWSSDK.Core` from `3.7.400.59` to `3.7.400.63`
- `AWSSDK.S3` from `3.7.410.1` to `3.7.410.5`
- `MongoDB.AspNetCore.OData` from `1.0.1` to `1.1.0`
- `Swashbuckle.AspNetCore` from `7.1.0` to `7.2.0`
- `Swashbuckle.AspNetCore.Annotations` from `7.1.0` to `7.2.0`
Updated the `Grand.Module.Api.csproj` file to reflect the new path for `MongoDB.AspNetCore.OData.dll` version `1.1.0`.
=> Update package versions and adjust MongoDB OData

src/Web/Grand.Web/Views/Wishlist/Components/EmailWishlist/Default.cshtml
Resolves issues/572 
Type: **feature|bugfix|**
Description of the issue this PR is solving:=> Email your wishlist to a friend is not working.
Why it's happening:=> JavaScript POST/Header/Content-Type is 'application/json'
How to reproduce it:=> 
Login as a 'buyer'. 
Add item to Wishlist'. 
Go to 'Wishlist'. 
Click the 'Email a Friend'. 
Fill in the 'Blanks'. 
Press the Submit button. 
Remove the ''Content-Type': 'application/json' in the POST Header
The fix: root\grandnode2\src\Web\Grand.Web\Views\Wishlist\Components\EmailWishlist\Default.cshtml
Remove: line 122: ==> 'Content-Type': 'application/json'
If you have a breaking changes, list them here, otherwise list none.
Login as a 'buyer'. 
Add item to Wishlist'. 
Go to 'Wishlist'. 
Click the 'Email a Friend'. 
Fill in the 'Blanks'. 
Press …
=> fixed: https://github.com/grandnode/grandnode2/issues/572

Directory.Packages.props, src/Business/Grand.Business.Catalog/Grand.Business.Catalog.csproj, src/Business/Grand.Business.Catalog/Services/ExportImport/Mapper/ProductProfile.cs
- Removed `MaxMind.GeoIP2` package version from `Directory.Packages.props` and its reference from `Grand.Business.Catalog.csproj`.
- Added new mapping conditions in `ProductProfile.cs` to improve property mapping control for `ProductDto` to `Product`.
=> Remove MaxMind.GeoIP2 package and fix import (update product by sku)

src/Business/Grand.Business.Customers/Services/VendorService.cs, src/Core/Grand.Infrastructure/Caching/Constants/VendorCacheKey.cs, src/Tests/Grand.Business.Customers.Tests/Services/VendorServiceTests.cs
Resolves #issueNumber  
Type: **feature|bugfix|**
Description of the issue this PR is solving, why it's happening, and how to reproduce it.
Summarize your solution to the problem. Please include short description.
If you have a breaking changes, list them here, otherwise list none.
1. List the steps needed for testing your PR.
2. Assume that everyone already know how to run the GrandNode, and do the basic configuration.
3. Be detailed enough that someone can work through it easily.
=> Add caching support to VendorService
